name: Build the package
on:
  push:
  pull_request:
jobs:
  uv-building:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: "Set up Python"
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41
        with:
          enable-cache: true

      - name: Set new version
        run: uv version

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build the project
        run: uv build
